title: Water Blog
description: Personal blog for writing and note-taking.
author: Chenglin Miao
avatar: /logo.jpeg
email: cmiao7@illinois.edu

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

Jekyll SEO Tag (Optional)
=========================
twitter:
  username: clmiao
  card: summary
logo: logo.jpeg
social:
  name: Chenglin Miao
  links:
    - https://www.linkedin.com/in/chenglin-miao-8a30b0272/
    - https://github.com/cmiao7-illinois
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
